joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

base_controller:
  type: "position_controllers/JointPositionController"
  joint: base_joint

link_1_controller:
  type: "position_controllers/JointPositionController"
  joint: r1_joint

link_2_controller:
  type: "position_controllers/JointPositionController"
  joint: r2_joint